# Generated by Django 5.1.1 on 2024-11-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.CharField(max_length=30)),
                ('client_phone', models.IntegerField()),
                ('client_alt_email', models.CharField(max_length=30, null=True)),
                ('client_alt_phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department_details',
            fields=[
                ('dept_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_location', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signup_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('re_password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_email', models.CharField(max_length=30, unique=True)),
                ('emp_phone', models.IntegerField(unique=True)),
                ('emp_role', models.CharField(max_length=30)),
                ('manager_id', models.IntegerField(null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department_details')),
            ],
        ),
        migrations.AddField(
            model_name='department_details',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_details'),
        ),
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('project_desc', models.CharField(max_length=200)),
                ('project_budget', models.CharField(max_length=20)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client_details')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department_details')),
            ],
        ),
    ]
