# Generated by Django 5.1.1 on 2024-11-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_details_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_details',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.employee_details'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.department_details'),
        ),
    ]
