# Generated by Django 5.1.1 on 2024-11-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_department_details_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='dept_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.department_details'),
        ),
    ]
